const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const titles={mission:'State Fertilizer Command Centre',farmgraph:'FarmGraph Nutrient & Fertilizer Digital Twin',formulation:'Governed Formulation Studio',demand:'DemandCast Probabilistic Forecasting',supply:'StockPulse + FlowOpt Supply Network',trace:'TraceGraph + Sentinel',sutra:'SUTRA-ID Edge Assisted Execution',pilot:'90-Day Pilot & Vision 2030',governance:'ModelOps, Integrations & Governance'};
const districts=[
{name:'Sikar',grade:'DAP',stock:4.2,p50:8.7,p90:10.9,cover:4.4,lead:18,trace:2,risk:'critical',x:59,y:27,signal:'Mustard-stage acceleration + SHC phosphorus-deficiency cluster'},
{name:'Jaipur',grade:'DAP',stock:8.5,p50:9.2,p90:11.0,cover:8.1,lead:12,trace:0,risk:'watch',x:61,y:38,signal:'Demand velocity rising; stock floor remains adequate'},
{name:'Bharatpur',grade:'UREA',stock:7.6,p50:6.1,p90:7.5,cover:10.8,lead:14,trace:1,risk:'stable',x:78,y:39,signal:'Stable service cover; one custody review'},
{name:'Alwar',grade:'DAP',stock:5.0,p50:6.4,p90:8.4,cover:6.2,lead:15,trace:1,risk:'watch',x:73,y:31,signal:'Rainfall recovery + dealer sales velocity'},
{name:'Kota',grade:'UREA',stock:9.1,p50:8.2,p90:9.4,cover:11.3,lead:16,trace:0,risk:'stable',x:69,y:64,signal:'Normal seasonal envelope'},
{name:'Bikaner',grade:'DAP',stock:7.4,p50:5.8,p90:7.1,cover:10.1,lead:21,trace:0,risk:'stable',x:36,y:24,signal:'Long lead time, adequate cover'},
{name:'Jodhpur',grade:'DAP',stock:8.8,p50:7.2,p90:8.9,cover:9.4,lead:19,trace:0,risk:'stable',x:35,y:49,signal:'Stable stock; route capacity normal'},
{name:'Udaipur',grade:'NPKS',stock:5.8,p50:5.1,p90:6.6,cover:8.6,lead:20,trace:1,risk:'watch',x:47,y:72,signal:'Mixed-crop demand uncertainty'},
{name:'Ajmer',grade:'DAP',stock:6.0,p50:5.5,p90:6.8,cover:8.9,lead:14,trace:0,risk:'stable',x:51,y:46,signal:'Stable'},
{name:'Barmer',grade:'UREA',stock:5.5,p50:4.2,p90:5.6,cover:9.8,lead:25,trace:0,risk:'stable',x:21,y:58,signal:'Remote lead-time sensitivity'},
{name:'Ganganagar',grade:'UREA',stock:6.6,p50:5.7,p90:7.4,cover:8.7,lead:22,trace:0,risk:'stable',x:30,y:10,signal:'Irrigated-area seasonal pattern'},
{name:'Chittorgarh',grade:'NPKS',stock:4.8,p50:4.9,p90:6.2,cover:7.1,lead:18,trace:1,risk:'watch',x:58,y:66,signal:'Crop mix + stock reconciliation lag'}
];
let selected=districts[0], events=[], transfers=[], sutraStep=0, synced=false, tampered=false;
const now=()=>new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
function log(title,detail){events.unshift({time:now(),title,detail});events=events.slice(0,12);renderFeed()}
function goto(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('#nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#pageTitle').textContent=titles[id];window.scrollTo({top:0,behavior:'smooth'})}
function renderHotspots(){const root=$('#hotspots');root.innerHTML='';districts.forEach(d=>{let b=document.createElement('button');b.className=`hotspot ${d.risk}${d===selected?' active':''}`;b.dataset.name=d.name;b.style.left=d.x+'%';b.style.top=d.y+'%';b.title=`${d.name}: ${d.grade} · ${d.cover}d P90 cover`;b.onclick=()=>{selected=d;renderHotspots();renderWorkbench()};root.appendChild(b)})}
function renderRows(){const root=$('#districtRows');root.innerHTML=districts.map(d=>`<tr data-d="${d.name}"><td><b>${d.name}</b></td><td>${d.grade}</td><td>${d.stock.toFixed(1)} kt</td><td>${d.p50.toFixed(1)} / ${d.p90.toFixed(1)} kt</td><td><b>${d.cover.toFixed(1)} d</b></td><td>${d.lead} h</td><td>${d.trace}</td><td><span class="risk ${d.risk}">${d.risk.toUpperCase()}</span></td></tr>`).join('');root.querySelectorAll('tr').forEach(r=>r.onclick=()=>{selected=districts.find(d=>d.name===r.dataset.d);renderHotspots();renderWorkbench()})}
function renderWorkbench(){let d=selected;let source=d.name==='Sikar'?districts.find(x=>x.name==='Jaipur'):districts.find(x=>x.risk==='stable'&&x.grade===d.grade)||districts[4];let qty=Math.max(.8,Math.min(2.2,(d.p90-d.stock)*.45)).toFixed(1);$('#workbench').innerHTML=`<div class="wb-title"><h3>${d.name} · ${d.grade}</h3><span class="risk ${d.risk}">${d.risk.toUpperCase()}</span></div><div class="wb-metrics"><div class="metric"><small>Local stock</small><b>${d.stock.toFixed(1)} kt</b></div><div class="metric"><small>P90 demand</small><b>${d.p90.toFixed(1)} kt</b></div><div class="metric"><small>P90 cover</small><b>${d.cover.toFixed(1)} days</b></div><div class="metric"><small>Lead time</small><b>${d.lead} h</b></div></div><div class="reason"><b>Top causal signal</b><br>${d.signal}</div><div class="guard"><span>Candidate source <b>${source.name}</b></span><span>Proposed transfer <b>${qty} kt</b></span><span>Source minimum cover after move <b>PASS · 7.2 d</b></span><span>Grade / route compatibility <b>PASS</b></span></div><div class="wb-actions"><button class="btn primary" id="approve">Authorize transfer</button><button class="btn ghost" id="defer">Override / defer</button></div>`;$('#approve').onclick=()=>authorize(d,source,+qty);$('#defer').onclick=()=>receipt('Officer Override',{'District':d.name,'Disposition':'DEFERRED','Reason':'Operational review requested','Authority':'Human officer'})}
function authorize(d,source,qty){const id='TR-'+Date.now().toString().slice(-6);transfers.unshift({id,source:source.name,dest:d.name,grade:d.grade,qty,state:'AUTHORIZED'});d.stock+=qty;d.cover=Math.min(12,d.cover+qty*1.1);if(d.cover>7)d.risk='watch';log('Transfer authorized',`${id} · ${source.name} → ${d.name} · ${qty} kt ${d.grade}`);renderRows();renderHotspots();renderWorkbench();renderTransfers();receipt('Decision Receipt',{'Decision ID':id,'Destination':d.name,'Source':source.name,'Grade':d.grade,'Quantity':qty+' kt','Guardrail':'source stock-floor PASS','Causal signal':d.signal,'Disposition':'AUTHORIZED BY HUMAN OFFICER','Trace state':'custody event created'})}
function receipt(title,obj){$('#modalTitle').textContent=title;$('#modalBody').innerHTML='<div class="receipt-grid">'+Object.entries(obj).map(([k,v])=>`<div>${k}</div><div><b>${v}</b></div>`).join('')+'</div>';$('#modal').classList.add('open')}
function renderFeed(){if(!events.length){events=[{time:now(),title:'Mission control initialized',detail:'Public aggregates loaded; synthetic district layer ready.'},{time:now(),title:'DemandCast shadow model healthy',detail:'P90 calibration monitor active.'},{time:now(),title:'SUTRA field queue',detail:'1 signed offline event awaiting sync.'}]};$('#feed').innerHTML=events.map(e=>`<div class="event"><time>${e.time}</time><div><b>${e.title}</b><span>${e.detail}</span></div></div>`).join('')}
const nodeInfo={Farmer:['FR-RJ-2048-0194','Authoritative Farmer-ID reference','reference only; no PII stored'],Plot:['PL-SK-2207','Authorized plot / Khasra reference','geometry/version would come from approved rail'],Crop:['Mustard · vegetative','Crop-cycle evidence','sowing/stage source time retained'],Soil:['SHC-SK-8821 · 8 months','Soil Health Card','12 parameters + sample/test date'],Weather:['IMD/KDSS adapter','Weather evidence','timestamped rainfall/forecast feature'],Nutrient:['RULE-RJ-17','Derived deterministic decision','rule version + inputs retained'],Demand:['P10/P50/P90','DemandCast derived state','model + feature version retained'],Stock:['Warehouse / dealer state','Authorized stock reference','physical/digital freshness retained'],Trace:['DAP-RJ-26-1842','TraceGraph event state','PII off-ledger; evidence hash + previous hash']};
function inspectNode(n){const x=nodeInfo[n];$('#inspector').innerHTML=`<h3>${n}</h3><div class="kv"><span>Current value</span><b>${x[0]}</b></div><div class="kv"><span>Authority</span><b>${x[1]}</b></div><div class="kv"><span>Lineage rule</span><b>${x[2]}</b></div><div class="kv"><span>Freshness</span><b>versioned · source time retained</b></div><div class="kv"><span>AI authority</span><b>read / derive / explain only</b></div>`}
function injectStress(){$('#weatherNode').textContent='rainfall recovery +18%';$('#demandNode').textContent='P90 12.4 kt ↑';selected=districts[0];selected.p90=12.4;selected.cover=3.8;selected.risk='critical';log('FarmGraph stress propagated','Weather + crop-stage feature update raised Sikar DAP P90 envelope.');renderRows();renderHotspots();renderWorkbench();inspectNode('Weather')}
const soils=[['pH','7.8'],['EC','0.42 dS/m'],['Organic C','0.39 %'],['N','214 kg/ha'],['P','8.4 kg/ha'],['K','286 kg/ha'],['S','9.1 ppm'],['Zn','0.54 ppm'],['Fe','6.8 ppm'],['Cu','0.46 ppm'],['Mn','4.7 ppm'],['B','0.58 ppm']];
function renderSoils(){$('#soilGrid').innerHTML=soils.map(([k,v])=>`<div class="soil"><small>${k}</small><b>${v}</b></div>`).join('')}
function formulate(){let stale=$('#shcAge').value==='stale';$('#rx').innerHTML=stale?`<div class="callout"><b>ABSTAIN / RETEST PATH</b><br>SHC is stale for the selected policy window. RAJ-NUTRI may explain the issue but cannot manufacture a fresh nutrient dose.</div>`:[['Validate source','SHC fresh · 12/12 parameters present'],['Resolve crop/stage',$('#crop').value+' · '+$('#stage').value],['Authorized agronomy rule','RULE-RJ-17 · deterministic'],['Permitted-product optimizer','DAP/NPKS feasibility checked against policy + stock'],['4R execution context','source · rate · time · place'],['RAJ-NUTRI explanation','Hindi/English grounded summary; numeric invention prohibited']].map((x,i)=>`<div class="rx-step"><i>${i+1}</i><div><b>${x[0]}</b><span>${x[1]}</span></div></div>`).join('');log('UrvaraRX executed',stale?'Stale SHC triggered abstention/retest.':'Deterministic nutrient path produced evidence-linked recommendation context.')}
function forecast(){let a=+$('input#area').value,r=+$('input#rain').value,s=+$('input#sales').value;let base=selected.p50*(1+a*.008+r*.003+s*.006);base=Math.max(2,base);let p10=base*.82,p50=base,p90=base*1.25;$('#quant').innerHTML=[['P10',p10],['P50',p50],['P90',p90]].map(([k,v])=>`<div><small>${k}</small><b>${v.toFixed(1)}</b><em>kt / 4 wk</em></div>`).join('');let vals=[p10*.7,p10*.82,p50*.87,p50,p90*.88,p90];let pts=vals.map((v,i)=>`${40+i*100},${185-v*10}`).join(' ');$('#chart').innerHTML=`<defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#5ca8d3" stop-opacity=".32"/><stop offset="1" stop-color="#5ca8d3" stop-opacity="0"/></linearGradient></defs><line x1="35" y1="185" x2="565" y2="185" stroke="#d7e3eb"/><polyline points="${pts}" fill="none" stroke="#0d5ea6" stroke-width="4"/><polygon points="40,185 ${pts} 540,185" fill="url(#g)"/>`;$('#forecastWhy').innerHTML=`<b>Scenario explanation:</b> crop area ${a>=0?'+':''}${a}%, rainfall ${r>=0?'+':''}${r}%, sales velocity ${s>=0?'+':''}${s}%. Production model would also use authorized movement/stock/crop/SHC features and stock-out censoring.`;log('DemandCast recomputed',`${$('#fcDistrict').value} ${$('#fcGrade').value} P90 = ${p90.toFixed(1)} kt.`)}
function renderWarehouses(){$('#warehouseRows').innerHTML=[['Jaipur RW','DAP',8200,8170,30,8.2,'stable'],['Sikar WH','DAP',4200,4175,25,4.4,'watch'],['Kota RW','UREA',9100,9094,6,11.3,'stable'],['Udaipur WH','NPKS',5800,5735,65,8.6,'review']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]} d</td><td>${r[6]}</td></tr>`).join('')}
function renderTransfers(){if(!transfers.length)transfers=[{id:'TR-48219',source:'Jaipur',dest:'Alwar',grade:'DAP',qty:1.2,state:'IN_TRANSIT'}];$('#transferQueue').innerHTML=transfers.map(t=>`<div class="order"><div><b>${t.id} · ${t.grade}</b><span>${t.source} → ${t.dest} · ${t.qty} kt</span></div><span class="badge ${t.state==='AUTHORIZED'?'safe':'warn'}">${t.state}</span></div>`).join('')}
const trace=[['DISPATCH','Manufacturer → Jaipur RW','hash 6f1d…'],['WAREHOUSE_RECEIPT','Jaipur RW','hash a39c…'],['TRANSFER','Jaipur → Sikar','hash 8b72…'],['DEALER_RECEIPT','Dealer cluster SK-04','hash c4e8…'],['FFS/POS_REFERENCE','Retail transaction ref','off-ledger identity reference'],['SUTRA_FIELD_ACK','Offline signed acknowledgement','hash f10a…']];
function renderTrace(){$('#timeline').innerHTML=trace.map((x,i)=>`<div class="trace-event ${tampered&&i===2?'bad':''}"><i></i><div><b>${x[0]}</b><span>${x[1]} · ${tampered&&i===2?'INVALID:'+x[2]:x[2]}</span></div></div>`).join('')}
function score(){let v=+$('select#sv').value+rnum('#sr')+rnum('#ss')+rnum('#sp');let level=v>=70?'HIGH-PRIORITY HUMAN REVIEW':v>=30?'HUMAN REVIEW':'MONITOR';$('#sentinelBadge').textContent=level;$('#sentinelBadge').className='badge '+(v>=70?'warn':v>=30?'human':'safe');$('#sentinelOut').innerHTML=`<b>Review score ${v}/105 · ${level}</b><br>Signals are prioritization evidence only. No automatic dealer accusation, subsidy denial, quality certification or enforcement.`;log('Sentinel scored',`${level} · score ${v}/105.`)}
const rnum=s=>+$(s).value;
function stepSutra(){sutraStep=Math.min(3,sutraStep+1);$$('#sutraSteps>div:not(.sutra-actions)').forEach((d,i)=>d.classList.toggle('active',i===sutraStep));log('SUTRA field workflow',`Advanced to assisted step ${sutraStep+1}.`)}
function syncSutra(){synced=true;$('#net').textContent='ONLINE';$('#net').className='badge safe';$('#queue').textContent='0 queued';$('#receiptState').textContent='ACKNOWLEDGED';$('#syncMsg').innerHTML='<b>Server ACK received.</b> EVT-SUTRA-74291 committed once; retry remains safe.';log('SUTRA sync acknowledged','Signed field event synchronized after connectivity restored.')}
function retrySutra(){if(!synced){$('#syncMsg').innerHTML='<b>Still offline.</b> Event remains locally queued with the same idempotency key.';return}$('#receiptState').textContent='DUPLICATE_SUPPRESSED';$('#syncMsg').innerHTML='<b>DUPLICATE_SUPPRESSED.</b> Same business-event ID retried; backend retained one committed event.';log('Duplicate suppressed','SUTRA retry proved idempotent business-event semantics.')}
const registry=[['iFMS / DBT','movement · sales · stock','CONTRACT_READY'],['FFS / DRS','fertilizer application / retail reference','CONTRACT_READY'],['Soil Health Card','12 soil parameters + State recommendation logic','CONTRACT_READY'],['AgriStack / DCS / KDSS','farmer · plot · crop context','CONTRACT_READY'],['IMD / approved weather','rainfall / forecast features','CONTRACT_READY'],['Raj Sewa Dwaar / approved State APIs','integration gateway','CONTRACT_READY'],['FCO / labs / COA','quality evidence','CONTRACT_READY'],['Kharif 2026 State aggregates','evaluator evidence','LIVE_PUBLIC'],['District operational signals','working simulation','DEMO_SANDBOX']];
function renderRegistry(){$('#registry').innerHTML=registry.map(r=>`<div class="reg"><b>${r[0]}</b><span>${r[1]}</span><span class="tag ${r[2]==='LIVE_PUBLIC'?'live':r[2]==='DEMO_SANDBOX'?'demo':'contract'}">${r[2]}</span></div>`).join('')}
function runJury(){const dock=$('#demoDock');dock.classList.add('show');const stages=[['1/7 · Detect','FarmGraph receives a weather/crop stress signal.','farmgraph',()=>injectStress()],['2/7 · Forecast','DemandCast widens Sikar DAP P90 uncertainty.','demand',()=>{$('#area').value=12;$('#rain').value=18;$('#sales').value=15;updateSliders();forecast()}],['3/7 · Decide','FlowOpt checks source floor and proposes a transfer.','mission',()=>{selected=districts[0];renderWorkbench()}],['4/7 · Authorize','Human officer authorizes; Decision Receipt created.','mission',()=>{let s=districts.find(x=>x.name==='Jaipur');authorize(selected,s,1.6)}],['5/7 · Trace','Custody chain follows the authorized movement.','trace',()=>renderTrace()],['6/7 · Field','SUTRA signs field acknowledgement offline then synchronizes.','sutra',()=>{sutraStep=3;stepSutra();syncSutra()}],['7/7 · Prove','Intentional retry is duplicate-suppressed; pilot impact gates remain measurable.','pilot',()=>retrySutra()]];let i=0;function next(){if(i>=stages.length){$('#demoStage').textContent='MISSION COMPLETE';$('#demoCopy').textContent='Prediction → governed decision → execution → evidence → offline sync → measurable pilot.';$('#demoProgress').style.width='100%';setTimeout(()=>dock.classList.remove('show'),5000);return}let st=stages[i];$('#demoStage').textContent=st[0];$('#demoCopy').textContent=st[1];$('#demoProgress').style.width=((i+1)/stages.length*100)+'%';goto(st[2]);setTimeout(()=>{st[3]();i++;setTimeout(next,1100)},500)}next()}
function updateSliders(){$('#areaOut').textContent=(+$('input#area').value>=0?'+':'')+$('#area').value+'%';$('#rainOut').textContent=(+$('input#rain').value>=0?'+':'')+$('#rain').value+'%';$('#salesOut').textContent=(+$('input#sales').value>=0?'+':'')+$('#sales').value+'%'}
function init(){setTimeout(()=>$('#boot').style.display='none',1150);$('#clock').textContent='Refreshed '+now();$$('#nav button[data-page], [data-goto]').forEach(b=>b.onclick=()=>goto(b.dataset.page||b.dataset.goto));$('#close').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};$('#reset').onclick=()=>location.reload();$('#jury').onclick=runJury;$('#stress').onclick=injectStress;$$('.node').forEach(n=>n.onclick=()=>inspectNode(n.dataset.node));$('#formulate').onclick=formulate;['area','rain','sales'].forEach(id=>$('#'+id).oninput=updateSliders);$('#forecast').onclick=forecast;$('#gps').onclick=()=>{$('#gpsText').textContent='GEOFENCE DEVIATION';log('GPS deviation detected','Selected in-transit DAP route entered human logistics review queue.')};$('#tamper').onclick=()=>{tampered=true;renderTrace();$('#kIntegrity').textContent='FAILED';log('Trace integrity exception','Custody-event hash mismatch detected; human review opened.')};$('#score').onclick=score;$('#nextSutra').onclick=stepSutra;$('#sync').onclick=syncSutra;$('#retry').onclick=retrySutra;renderHotspots();renderRows();renderWorkbench();renderFeed();renderSoils();renderWarehouses();renderTransfers();renderTrace();renderRegistry();districts.forEach(d=>$('#fcDistrict').insertAdjacentHTML('beforeend',`<option>${d.name}</option>`));$('#fcDistrict').value='Sikar';updateSliders();forecast();$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'){let q=e.target.value.toLowerCase(),d=districts.find(x=>x.name.toLowerCase().includes(q));if(d){selected=d;goto('mission');renderHotspots();renderWorkbench()}}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')$('#modal').classList.remove('open')})}
document.addEventListener('DOMContentLoaded',init);