(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const titles={command:'Executive Fertilizer Command Centre',map:'Allocation Twin & Rajasthan Operational Map',forecast:'DemandCast · Probabilistic Demand Intelligence',nutrient:'NutrientTwin / UrvaraRX · Plot Decision Layer',trace:'TraceGraph · Bag-to-Bigha Chain of Custody',sentinel:'Quality & Leakage Sentinel · Human Review',sutra:'SUTRA-ID Edge · Assisted Offline Field Channel',policy:'Balanced-Use Policy Laboratory',governance:'Integration & Model Governance Registry'};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function switchTab(tab){$$('.nav-btn,.tab').forEach(x=>x.classList.remove('active'));const b=$(`.nav-btn[data-tab="${tab}"]`), s=$(`#${tab}`);if(b)b.classList.add('active');if(s)s.classList.add('active');$('#pageTitle').textContent=titles[tab]||'RAJ-URVARA AI';window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.jump)));

const boot=[['Validating public evidence…',24],['Loading model registry…',48],['Checking trace schemas…',69],['Preparing evaluator sandbox…',88],['RAJ-URVARA ready',100]];let bi=0;function nextBoot(){if(bi>=boot.length){setTimeout(()=>$('#splash').classList.add('hide'),320);return}$('#bootText').textContent=boot[bi][0];$('#bootBar').style.width=boot[bi][1]+'%';bi++;setTimeout(nextBoot,260)}setTimeout(nextBoot,120);

const fert=[{n:'UREA',r:6.71,a:11.31,s:8.05,st:3.27},{n:'DAP',r:3.21,a:2.73,s:2.08,st:.65},{n:'MOP',r:.05,a:.15,s:.05,st:.10},{n:'NPKS',r:.77,a:1.40,s:.68,st:.72}], max=11.5;
$('#fertChart').innerHTML=fert.map(x=>`<div class="fert-row"><strong>${x.n}</strong><div class="bar-stack"><div class="barline req"><i style="width:${x.r/max*100}%"></i></div><div class="barline avail"><i style="width:${x.a/max*100}%"></i></div><div class="barline sale"><i style="width:${x.s/max*100}%"></i></div></div><div class="fert-values"><b>${x.r.toFixed(2)}</b> req · <b>${x.a.toFixed(2)}</b> avail<br><b>${x.s.toFixed(2)}</b> sales · ${x.st.toFixed(2)} stock</div></div>`).join('');
const exBase=[['North-East DAP Watch','P90 cover 5.2 days · simulated demand acceleration','HIGH'],['Western Urea Watch','Sales velocity above demo seasonal baseline','WATCH'],['South-East NPKS Rebalance','0.08 LMT simulated transfer opportunity','ACTION']];function renderExceptions(stress=false){const arr=stress?[['North-East DAP Critical','P90 cover fell to 3.4 days after rainfall/crop stress','HIGH'],...exBase.slice(1)]:exBase;$('#exceptions').innerHTML=arr.map(x=>`<div class="exception ${x[2]=='HIGH'?'high':''}"><div><b>${x[0]}</b><p>${x[1]}</p></div><span class="badge ${x[2]=='HIGH'?'danger':x[2]=='WATCH'?'warn':'info'}">${x[2]}</span></div>`).join('')}renderExceptions();
$$('.counter').forEach(el=>{const target=+el.dataset.target;let t0=null;function f(ts){t0??=ts;let p=Math.min(1,(ts-t0)/850),v=target*p;el.textContent=v.toFixed(1);if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)});

const clusters=[{id:'ne',name:'North-East DAP Watch',x:412,y:177,status:'high',cover:5.2,p90:'0.23 LMT',stock:'0.12 LMT',lead:'2.1 days',action:'Stage a 0.04 LMT DAP transfer from a surplus demo node; preserve a 7-day minimum source stock-cover floor; officer approval required.'},{id:'west',name:'Western Urea Watch',x:190,y:235,status:'watch',cover:8.8,p90:'0.31 LMT',stock:'0.29 LMT',lead:'3.0 days',action:'No transfer yet. Raise monitoring cadence and hold a reserve option; re-run after updated sales/weather signal.'},{id:'se',name:'South-East NPKS Rebalance',x:403,y:320,status:'stable',cover:13.1,p90:'0.10 LMT',stock:'0.14 LMT',lead:'1.6 days',action:'Eligible source node for a small human-approved NPKS rebalance while maintaining minimum local service level.'},{id:'north',name:'Northern Logistics Node',x:265,y:106,status:'stable',cover:14.7,p90:'0.12 LMT',stock:'0.18 LMT',lead:'2.6 days',action:'Stable demo node. No action required.'},{id:'south',name:'Southern Field Node',x:282,y:356,status:'watch',cover:9.6,p90:'0.09 LMT',stock:'0.08 LMT',lead:'2.3 days',action:'Monitor crop-stage transition before moving stock.'}];
const svg=$('#rjMap');clusters.forEach(c=>{const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('class',`map-marker ${c.status}`);g.dataset.id=c.id;g.innerHTML=`<circle class="outer" cx="${c.x}" cy="${c.y}" r="12"></circle><circle class="core" cx="${c.x}" cy="${c.y}" r="6"></circle><text x="${c.x+12}" y="${c.y+4}">${c.name.split(' ')[0]}</text>`;g.addEventListener('click',()=>selectCluster(c.id));svg.appendChild(g)});
function selectCluster(id){const c=clusters.find(x=>x.id===id)||clusters[0];$$('.map-marker').forEach(g=>g.classList.toggle('selected',g.dataset.id===id));$('#clusterName').textContent=c.name;$('#clusterMeta').innerHTML=`<div><span>P90 stock cover</span><b>${c.cover} days</b></div><div><span>4-week P90</span><b>${c.p90}</b></div><div><span>Local stock</span><b>${c.stock}</b></div><div><span>Transfer lead</span><b>${c.lead}</b></div>`;$('#allocationRecommendation').textContent=c.action}selectCluster('ne');
$$('.chip').forEach(ch=>ch.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('active'));ch.classList.add('active');toast(`${ch.textContent} layer selected · demo values`) }));
$('#approveTransfer').addEventListener('click',()=>{toast('Officer approval recorded · demo transfer event created');$('#allocationRecommendation').innerHTML='<b>APPROVED · DEMO</b><br>Transfer order staged with minimum stock-cover constraint and reason-coded authorization.'});$('#overrideTransfer').addEventListener('click',()=>toast('Override captured with required reason code · DEMO'));

function recalc(){const area=+$('#area').value,rain=+$('#rain').value,p=$('#product').value,post=$('#posture').value;$('#areaLabel').textContent=(area>=0?'+':'')+area+'%';$('#rainLabel').textContent=(rain>=0?'+':'')+rain+'%';const base={DAP:.82,UREA:1.47,NPKS:.36,MOP:.08}[p];let rainFactor=1+Math.max(-.16,Math.min(.18,rain*.003));let p50=base*(1+area/100)*rainFactor;let spread=p50*(post==='high'?.16:.12);let vals=[Math.max(0,p50-1.28*spread),p50,p50+1.28*spread];$('#forecastCards').innerHTML=['P10','P50','P90'].map((n,i)=>`<div class="fcard"><span>${n}</span><b>${vals[i].toFixed(2)} LMT</b><small>${p} · 4-week demo envelope</small></div>`).join('');const heights=[.54,.67,.72,.63,.78,.84,.9,.74,.95,.88,.81,.91].map((v,i)=>Math.max(.15,Math.min(1,v*(1+area/100)*(1+(i>6?rain*.002:0)))));$('#forecastCurve').innerHTML=heights.map(v=>`<i style="height:${Math.round(v*88)}px"></i>`).join('');return vals}
['area','rain','product','posture'].forEach(id=>$(`#${id}`).addEventListener('input',recalc));$('#runScenario').addEventListener('click',()=>{recalc();toast('Forecast envelope recomputed · DEMO_SANDBOX')});recalc();

$('#assessNutrient').addEventListener('click',()=>{const n=+$('#nVal').value,p=+$('#pVal').value,k=+$('#kVal').value,oc=+$('#ocVal').value;let score=0,re=[];if(n<40){score+=3;re.push('N indicator low')}else if(n<60){score++;re.push('N indicator moderate')}if(p<35){score+=2;re.push('P indicator low')}if(k<45){score+=2;re.push('K indicator low')}if(oc<.5){score+=2;re.push('organic carbon indicator low')}const cls=score>=6?'HIGH':score>=3?'MEDIUM':'LOW';$('#nutrientResult').innerHTML=`<div class="decision-icon">${cls==='LOW'?'✓':'!'}</div><div><b>${cls} deficiency-risk index · ${score}/9</b><p>${re.join(' · ')||'No demo threshold triggered'}.</p><p><strong>Production path:</strong> retrieve authorized SHC/STCR recommendation → apply crop-stage rule → constrained permitted-product/stock optimizer → source-backed explanation. No dose is generated by this demo.</p></div>`;toast('Nutrient risk assessed without generative dosing')});

const events=[['08:42','DISPATCH','Manufacturer/port lot sealed · event hash 9f3…a21','SIGNED'],['13:18','WAREHOUSE RECEIPT','Warehouse receipt + geofence evidence hash','VALID'],['Next day 09:14','TRANSFER','Dealer consignment released · vehicle ref pseudonymized','VALID'],['11:02','DEALER RECEIPT','QR/lot scan accepted · inventory event','VALID'],['15:37','RETAIL SALE','FFS/PoS reference linked · farmer PII remains off-chain','LINKED']];function renderTimeline(extra=false){let a=[...events];if(extra)a.push(['16:04','FIELD ACK','SUTRA offline receipt synchronized idempotently','SYNCED']);$('#timeline').innerHTML=a.map((e,i)=>`<div class="trow"><span class="tdot">${i+1}</span><time>${e[0]}</time><div><b>${e[1]}</b><p>${e[2]}</p></div><span class="badge ${e[3]==='SIGNED'||e[3]==='VALID'||e[3]==='SYNCED'?'good':'info'}">${e[3]}</span></div>`).join('')}renderTimeline();
function updateVol(){$('#volLabel').textContent=(+$('#vol').value/100).toFixed(1)+'×'}$('#vol').addEventListener('input',updateVol);updateVol();$('#scoreAnomaly').addEventListener('click',()=>{let r=0,rs=[],vr=+$('#vol').value/100;if(vr>2){r+=30;rs.push('volume materially exceeds reference pattern')}if($('#routeDev').checked){r+=22;rs.push('route/geofence deviation')}if($('#repeat').checked){r+=18;rs.push('rapid repeated transaction pattern')}if($('#mismatch').checked){r+=30;rs.push('digital/physical stock mismatch')}if($('#identityConflict').checked){r+=18;rs.push('entitlement/land-reference conflict')}r=Math.min(100,r);$('#riskGauge').querySelector('b').textContent=r;$('#riskGauge').style.background=`conic-gradient(${r>=60?'#c83e4d':r>=35?'#c58012':'#0b4f93'} ${r*3.6}deg,#e8eff5 0deg)`;$('#riskReasons').innerHTML=`<div><b>${r>=60?'HIGH-PRIORITY HUMAN REVIEW':r>=35?'HUMAN REVIEW':'MONITOR'}</b><p>${rs.join(' · ')||'No selected anomaly feature.'}</p><p>No automatic subsidy denial or enforcement.</p></div>`});

$('#syncBtn').addEventListener('click',()=>{const b=$('#syncBtn');b.disabled=true;b.textContent='Synchronizing signed queue…';setTimeout(()=>{$('#offlinePill').textContent='SYNCED';$('#offlinePill').className='badge good';$('#queueCount').textContent='0';$('#queueMetric').innerHTML='00 <small>events</small>';renderTimeline(true);b.textContent='Acknowledgement received · idempotent';toast('SUTRA signed event synchronized · DEMO')},850)});
function policyCalc(){const r=+$('#reduction').value,s=+$('#subsidy').value;$('#reductionLabel').textContent=r+'%';$('#subsidyLabel').textContent='₹'+s.toLocaleString('en-IN')+' Cr';const saved=s*r/100;$('#savedSubsidy').textContent='₹'+saved.toFixed(0)+' Cr';$('#formulaValue').textContent='₹'+(saved*.5).toFixed(0)+' Cr'}['reduction','subsidy'].forEach(id=>$(`#${id}`).addEventListener('input',policyCalc));policyCalc();

const tour=[['command','Why RAJ-URVARA','Start with the current public fertilizer position, then show the closed-loop architecture instead of presenting isolated AI features.'],['map','State Allocation Twin','Synthetic operational signals demonstrate uncertainty-aware, fairness-constrained and human-approved stock steering.'],['forecast','DemandCast','Show P10/P50/P90 and the release gates. The model never hides uncertainty.'],['nutrient','NutrientTwin + RAJ-NUTRI','The key safety claim: deterministic agronomy sets numeric values; the SLM only retrieves, calls tools and explains.'],['trace','TraceGraph','Prove custody without putting farmer PII on a ledger.'],['sutra','SUTRA-ID Edge','Finish with offline assisted field execution and signed sync — an optional last-mile channel, not mandatory hardware.']];let ti=0;function showTour(){const [tab,title,text]=tour[ti];switchTab(tab);$('#tourStepLabel').textContent=`${ti+1} / ${tour.length}`;$('#tourTitle').textContent=title;$('#tourText').textContent=text;$('#tourOverlay').hidden=false;$$('.tour-highlight').forEach(x=>x.classList.remove('tour-highlight'));const target=$(`#${tab} .panel`)||$(`#${tab} .hero-card`);if(target)target.classList.add('tour-highlight')}$('#tourBtn').addEventListener('click',()=>{ti=0;showTour()});$('#tourNext').addEventListener('click',()=>{ti++;if(ti>=tour.length){$('#tourOverlay').hidden=true;$$('.tour-highlight').forEach(x=>x.classList.remove('tour-highlight'));toast('Evaluator tour complete');return}showTour()});$('#tourExit').addEventListener('click',()=>{$('#tourOverlay').hidden=true;$$('.tour-highlight').forEach(x=>x.classList.remove('tour-highlight'))});

let stressRunning=false;$('#stressBtn').addEventListener('click',async()=>{if(stressRunning)return;stressRunning=true;const btn=$('#stressBtn');btn.disabled=true;const wait=ms=>new Promise(r=>setTimeout(r,ms));try{switchTab('forecast');toast('1/5 · Rainfall + crop-stage stress injected');$('#rain').value='28';$('#area').value='12';$('#product').value='DAP';$('#posture').value='high';recalc();$('#forecast').classList.add('stress-active');await wait(900);switchTab('map');clusters[0].cover=3.4;clusters[0].p90='0.29 LMT';selectCluster('ne');renderExceptions(true);$('#watchMetric').innerHTML='04 <small>clusters</small>';toast('2/5 · Allocation Twin raised DAP P90 service risk');await wait(900);$('#approveTransfer').click();toast('3/5 · Human-approved demo transfer staged');await wait(800);switchTab('trace');$('#chainBadge').textContent='Transfer custody active';renderTimeline(false);toast('4/5 · TraceGraph opened tamper-evident custody events');await wait(900);switchTab('sutra');$('#offlinePill').textContent='OFFLINE · RECEIVED';$('#queueCount').textContent='1';toast('5/5 · SUTRA recorded signed field receipt offline');await wait(900);$('#syncBtn').disabled=false;$('#syncBtn').textContent='Complete demo sync';$('#syncBtn').click();await wait(1100);switchTab('command');$('#traceMetric').innerHTML='99.1 <small>%</small>';$('#exceptionCount').textContent='6 active';toast('Closed loop complete · forecast → approval → custody → offline receipt → sync')}finally{btn.disabled=false;stressRunning=false}});
})();